"""adding admin table

Revision ID: 57da6002922a
Revises: 02987bad5565
Create Date: 2024-06-01 14:38:48.730171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57da6002922a'
down_revision = '02987bad5565'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admins')
    # ### end Alembic commands ###
