"""Add cascade delete to User-Login relationship

Revision ID: d19db0563634
Revises: 7bf7743e093a
Create Date: 2024-07-24 20:53:39.817738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd19db0563634'
down_revision = '7bf7743e093a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logins', schema=None) as batch_op:
        batch_op.drop_constraint('fk_logins_user_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_logins_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logins', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_logins_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_logins_user_id_users', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
